# Generated by Django 5.0 on 2023-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logare', '0006_remove_book_profiles_inchiriat_carte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inchiriat_carte',
            name='book',
        ),
        migrations.AddField(
            model_name='inchiriat_carte',
            name='book',
            field=models.ManyToManyField(to='logare.book'),
        ),
    ]
