# Generated by Django 5.0 on 2023-12-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logare', '0007_remove_inchiriat_carte_book_inchiriat_carte_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inchiriat_Carte',
        ),
    ]
