# Generated by Django 5.0 on 2023-12-17 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logare', '0009_inchiriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='inchiriere',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logare.book'),
        ),
    ]
