# Generated by Django 5.0 on 2023-12-18 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logare', '0010_inchiriere_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='inchiriere',
            name='data_inchiriere',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
