# Generated by Django 5.0 on 2023-12-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logare', '0012_inchiriere_data_returnare_estimata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inchiriere',
            name='data_returnare_estimata',
        ),
    ]
